arcgis_username = "JustSolo27"
arcgis_password = "ARCNatur@2021"
openai_api_key = "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"

[gcp]
type = "service_account"
project_id = "consultcofee"
private_key_id = "0ac309ad66a17768f89d316366d231b178533922"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQClCqT5hxJPG1dq
f/Fdb0pqyjp+26br8V+Z4G9PgI0T910JLW7qD4LjZTn3oPzIQ9/6iRCgFbPPVHvBX
bJHYrj+pl8Av22xluvhmF2ecX3X8YiwJJBXVwT1+yi/uZb/MiKXIhMTbVwRVXX3gq
vaRLhj8VQNmopgQTnPKyKB5fntmT10vKOQZoTT8NkgPkJebrFn2mih2y724y+6ngx
1OFR2Xau+uw8CE5PLy8N9ueXTSfQ+Nhau1EleH51CxnQ+ZpBHGEvWh1/DhLcsM6Zp
AZauwaa0vsJ+PNcjbx9IZIf6KrtyTbwqiXGyFdVEGshT8J9vg/8cxD8zbHqbIh3P/
KT9FAgMBAAECggEADoiPKcPpuZtrJU0Y+diA3TFypz7HnIG8084hCSvvaCdNfcH2e
zE5qz8ZyGY6Edxadhi8GPD2ar8UI3KIpbnJn2cSi3zw+mRlJD6g/foKkORd0YSBPg
qWgy9dbN3yT/poHep5j17AepCFWLDa5ONR++66sn1eu3O7yow2q+pZiB8rkftcxpU
twr+HXERsnAkINl8/tptAjo4ry5YzDcK3+X67aXCXzg4w9ASdsFg6P5OvdKpJICSj
gon3WE5opcxNaAW73QwVC5WZI8WvQ3ydP7zOV5N382ynhbfsglFEd8PrPmCqfY89N
4ukpMkYo2D9a9DrN1qUD54X2cRZ7+mEgQKBgQD/2ZWkY277pP44aw23+ccYnWc4kW
DB4545QGz873iEIGnr1ADOXa4EWvQuE63pGvLWUV8IIPkcdVaZ4b42CnlrdArvTvm
URBNJ5NsnEZmC7u/BVyGnVpQ+qmYtwXix9668Fi3/q0thG/YgM86eVYz8aM0m7BM2
zZL/uw+DlqK/9wKBgQDxPpafBCkfhKKWoEB8/0KIYkJVPKB+RHrEEhV0YtIouOFA4
78sXjJM/BbPpOqTMRuXbxm/wURzHqSrjvAGMFCMJBVQqgSeTJGGA7/nc7YvGPSFMS
xcCN28OhzLSxlKU4/aAozWXO/cxrnqdjNH29Uokk3ubUIPpPX/djhjyrtjgQKBgCwm
MtFcKzGXZhr8NjDSFE4mE0LKq2Spz4rXmDcJZ8V9BmogekciGT49J7evw6ne8ZqUD
g8MCZCkmt4Q+069/ffR3XUwLpcsLBvrNvoF6nSSoKK/U1pZ8Vji9KDequIi+G8ScLu
WpnpKZe1mozflUV/ZAdW+lQ426S/h6qptWwY/AoGAL9tzs932bns4adsmj+VvhHDBq
fkZ+ZKKLCVOPkVwXYW3odDMVvfk0KLdv5l+s251g8gVepXTh2bX0fTMJt4kzHhIBjW
ELwcPg19xDXBF/vfbYiTMIQHdQv7gQXAHd1g2XFBPMiNDri96KEoEiEfS9HZ5oUfpa
AMYjfIc46cPH4ECgYEAh+uS03nD6GgqUmd0uS64qrjdli8ynSQCL+MevLTfxoo/l8+
vJt/tw/C8M+buEXiPWHWaPAo5lXl7gkwA+Hb3Rl8q0c8vhT2elFfJMWS57HyTdXv63
vHSA/PZcVG520ky5UeP+qqZaKgZ5ZqZhmCPkhLm4wCa654KrK5u4sGikQA==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-sheets-writer-463@consultcofee.iam.gserviceaccount.com"
client_id = "101340279771435131565"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-writer-463@consultcofee.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
